# Generated by Django 6.0.6 on 2026-06-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_customer_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Último costo de compra'),
        ),
    ]
