# Generated by Django 6.0.6 on 2026-07-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_brand_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], max_length=15, null=True, verbose_name='Forma de pago'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de barras'),
        ),
    ]
