# Generated by Django 6.0.6 on 2026-07-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_invoice_forma_pago_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=5, verbose_name='Stock mínimo'),
        ),
    ]
