# Generated by Django 6.0.6 on 2026-07-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_product_fecha_vencimiento_product_stock_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('paypal', 'PayPal')], max_length=15, null=True, verbose_name='Forma de pago'),
        ),
    ]
