# Generated by Django 6.0.6 on 2026-07-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_backfill_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='interes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Interés'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='meses_credito',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Meses para diferir'),
        ),
    ]
