# Generated by Django 6.0.6 on 2026-07-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_invoice_meses_credito_interes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='monto_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto recibido en efectivo'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('paypal', 'PayPal')], max_length=15, null=True, verbose_name='Forma de pago'),
        ),
    ]
