# Generated by Django 6.0.6 on 2026-07-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_invoice_monto_recibido_alter_invoice_forma_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'permissions': [('access_brand_module', 'Acceso al módulo de marcas')], 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('access_customer_module', 'Acceso al módulo de clientes')], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date'], 'permissions': [('access_invoice_module', 'Acceso al módulo de facturas')], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('access_product_module', 'Acceso al módulo de productos')], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ['name'], 'permissions': [('access_productgroup_module', 'Acceso al módulo de grupos de productos')], 'verbose_name': 'Grupo de Producto', 'verbose_name_plural': 'Grupos de Productos'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'permissions': [('access_supplier_module', 'Acceso al módulo de proveedores')], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
