# Generated by Django 6.0.6 on 2026-07-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_alter_brand_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'permissions': [('access_brand_module', 'Acceso al módulo de marcas'), ('export_pdf_brand', 'Puede exportar marcas a PDF'), ('export_excel_brand', 'Puede exportar marcas a Excel')], 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('access_customer_module', 'Acceso al módulo de clientes'), ('export_pdf_customer', 'Puede exportar clientes a PDF'), ('export_excel_customer', 'Puede exportar clientes a Excel')], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date'], 'permissions': [('access_invoice_module', 'Acceso al módulo de facturas'), ('export_pdf_invoice', 'Puede exportar facturas a PDF'), ('export_excel_invoice', 'Puede exportar facturas a Excel'), ('send_whatsapp_invoice', 'Puede enviar recordatorio de pago por WhatsApp')], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('access_product_module', 'Acceso al módulo de productos'), ('export_pdf_product', 'Puede exportar productos a PDF'), ('export_excel_product', 'Puede exportar productos a Excel')], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ['name'], 'permissions': [('access_productgroup_module', 'Acceso al módulo de grupos de productos'), ('export_pdf_productgroup', 'Puede exportar grupos de productos a PDF'), ('export_excel_productgroup', 'Puede exportar grupos de productos a Excel')], 'verbose_name': 'Grupo de Producto', 'verbose_name_plural': 'Grupos de Productos'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'permissions': [('access_supplier_module', 'Acceso al módulo de proveedores'), ('export_pdf_supplier', 'Puede exportar proveedores a PDF'), ('export_excel_supplier', 'Puede exportar proveedores a Excel')], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
