# Generated by Django 6.0.6 on 2026-07-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_alter_brand_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tarjeta_expiracion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de expiración de la tarjeta'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tarjeta_titular',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Titular de la tarjeta'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tarjeta_ultimos_digitos',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Últimos 4 dígitos'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('paypal', 'PayPal')], max_length=15, null=True, verbose_name='Forma de pago'),
        ),
    ]
