# Generated by Django 6.0.6 on 2026-07-15 05:30

from django.db import migrations, models


def backfill_tipo_identificacion(apps, schema_editor):
    """Antes de este cambio, todo Customer.dni era cédula (10 dígitos) o RUC
    (13 dígitos) — nunca pasaporte (opción que no existía). Se infiere por
    longitud una sola vez acá; de ahí en adelante tipo_identificacion queda
    fijado explícitamente al crear/editar cada cliente."""
    Customer = apps.get_model('billing', 'Customer')
    for customer in Customer.objects.all():
        tipo = 'ruc' if len(customer.dni) == 13 else 'cedula'
        if customer.tipo_identificacion != tipo:
            customer.tipo_identificacion = tipo
            customer.save(update_fields=['tipo_identificacion'])


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_invoice_tarjeta_expiracion_invoice_tarjeta_titular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tipo_identificacion',
            field=models.CharField(choices=[('cedula', 'Cédula'), ('ruc', 'RUC'), ('pasaporte', 'Pasaporte')], default='cedula', max_length=10, verbose_name='Tipo de identificación'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dni',
            field=models.CharField(max_length=20, unique=True, verbose_name='Cédula / RUC / Pasaporte'),
        ),
        migrations.RunPython(backfill_tipo_identificacion, migrations.RunPython.noop),
    ]
