# Generated by Django 6.0.6 on 2026-07-13 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0014_alter_brand_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteElectronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(default='01', max_length=2, verbose_name='Tipo de comprobante')),
                ('ambiente', models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], default='1', max_length=1, verbose_name='Ambiente')),
                ('establecimiento', models.CharField(max_length=3, verbose_name='Establecimiento')),
                ('punto_emision', models.CharField(max_length=3, verbose_name='Punto de emisión')),
                ('secuencial', models.CharField(max_length=9, verbose_name='Secuencial')),
                ('clave_acceso', models.CharField(max_length=49, unique=True, verbose_name='Clave de acceso')),
                ('estado', models.CharField(choices=[('generado', 'XML generado'), ('firmado', 'XML firmado'), ('enviado', 'Enviado al SRI'), ('recibida', 'Recibida por el SRI'), ('devuelta', 'Devuelta por el SRI'), ('en_proceso', 'En procesamiento'), ('autorizado', 'Autorizado'), ('no_autorizado', 'No autorizado'), ('error', 'Error')], default='generado', max_length=15, verbose_name='Estado')),
                ('xml_generado', models.TextField(blank=True, verbose_name='XML sin firmar')),
                ('xml_firmado', models.TextField(blank=True, verbose_name='XML firmado')),
                ('xml_autorizado', models.TextField(blank=True, verbose_name='XML autorizado (con el comprobante del SRI)')),
                ('numero_autorizacion', models.CharField(blank=True, max_length=49, verbose_name='Número de autorización')),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de autorización')),
                ('mensajes', models.JSONField(blank=True, default=list, verbose_name='Mensajes')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comprobante_electronico', to='billing.invoice', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Comprobante Electrónico',
                'verbose_name_plural': 'Comprobantes Electrónicos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SecuencialSRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento', models.CharField(max_length=3)),
                ('punto_emision', models.CharField(max_length=3)),
                ('tipo_comprobante', models.CharField(default='01', max_length=2)),
                ('ultimo_secuencial', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Secuencial SRI',
                'verbose_name_plural': 'Secuenciales SRI',
                'constraints': [models.UniqueConstraint(fields=('establecimiento', 'punto_emision', 'tipo_comprobante'), name='unique_secuencial_sri_por_serie')],
            },
        ),
    ]
