# Generated by Django 6.0.6 on 2026-07-12 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('stock_bajo', 'Stock bajo'), ('producto_vence', 'Producto por vencer'), ('pago_pendiente', 'Pago pendiente'), ('caja_alerta', 'Alerta de caja')], max_length=20, verbose_name='Tipo')),
                ('nivel', models.CharField(choices=[('info', 'Info'), ('warning', 'Advertencia'), ('danger', 'Crítico')], default='warning', max_length=10, verbose_name='Nivel')),
                ('mensaje', models.CharField(max_length=255, verbose_name='Mensaje')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='Enlace')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('clave', models.CharField(max_length=100, verbose_name='Clave')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('leida', False)), fields=('clave',), name='unica_no_leida_por_clave')],
            },
        ),
    ]
