# Generated by Django 6.0.6 on 2026-07-09 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchasing', '0003_purchase_estado_purchase_saldo_purchase_tipo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de pago')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='purchasing.purchase', verbose_name='Compra')),
            ],
            options={
                'verbose_name': 'Pago de Compra',
                'verbose_name_plural': 'Pagos de Compras',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
