# Generated by Django 6.0.6 on 2026-07-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocompra',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('paypal', 'PayPal')], default='efectivo', max_length=15, verbose_name='Forma de pago'),
        ),
    ]
