# Generated by Django 6.0.6 on 2026-07-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_pagocompra_forma_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocompra',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('paypal', 'PayPal')], default='efectivo', max_length=15, verbose_name='Forma de pago'),
        ),
    ]
