# Generated by Django 6.0.6 on 2026-07-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_pagocompra_forma_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagocompra',
            options={'ordering': ['-fecha', '-id'], 'permissions': [('access_pagocompra_module', 'Acceso al módulo de pagos a proveedores')], 'verbose_name': 'Pago de Compra', 'verbose_name_plural': 'Pagos de Compras'},
        ),
    ]
