# Generated by Django 6.0.6 on 2026-07-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_pagocompra_tarjeta_cvv_pagocompra_tarjeta_expiracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocompra',
            name='paypal_payout_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de payout de PayPal'),
        ),
    ]
