# Generated by Django 6.0.6 on 2026-07-12 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0008_product_fecha_vencimiento_product_stock_minimo'),
        ('cobros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenPaypal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_order_id', models.CharField(max_length=50, unique=True, verbose_name='ID de orden PayPal')),
                ('tipo', models.CharField(choices=[('venta', 'Venta'), ('cobro', 'Cobro de factura')], max_length=10, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('creada', 'Creada'), ('capturada', 'Capturada'), ('cancelada', 'Cancelada'), ('fallida', 'Fallida')], default='creada', max_length=10, verbose_name='Estado')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('payload', models.JSONField(verbose_name='Datos de la operación')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('cobro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_paypal', to='cobros.cobrofactura', verbose_name='Cobro generado')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_paypal', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_paypal', to='billing.invoice', verbose_name='Factura generada')),
            ],
            options={
                'verbose_name': 'Orden de PayPal',
                'verbose_name_plural': 'Órdenes de PayPal',
                'ordering': ['-creado_en'],
            },
        ),
    ]
