# Generated by Django 6.0.6 on 2026-07-12 20:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_nombre', models.CharField(default='TecnoStock S.A.', max_length=200, verbose_name='Nombre de la empresa')),
                ('empresa_ruc', models.CharField(blank=True, max_length=13, verbose_name='RUC')),
                ('empresa_direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('empresa_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='IVA (%)')),
                ('moneda_simbolo', models.CharField(default='$', max_length=5, verbose_name='Símbolo de moneda')),
                ('stock_minimo_default', models.PositiveIntegerField(default=5, verbose_name='Stock mínimo por defecto (productos nuevos)')),
                ('credito_porcentaje_por_compras', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, verbose_name='% de crédito por compras históricas')),
                ('dias_aviso_vencimiento_producto', models.PositiveIntegerField(default=30, verbose_name='Días de aviso: producto por vencer')),
                ('dias_aviso_pago_compra', models.PositiveIntegerField(default=5, verbose_name='Días de aviso: pago de compra pendiente')),
                ('dias_credito_factura_default', models.PositiveIntegerField(default=30, verbose_name='Días de plazo por defecto (facturas a crédito sin perfil)')),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'verbose_name_plural': 'Configuración del sistema',
            },
        ),
    ]
