# Generated by Django 6.0.6 on 2026-07-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='sri_establecimiento',
            field=models.CharField(default='001', max_length=3, verbose_name='Código de establecimiento (SRI)'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='sri_nombre_comercial',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre comercial (si difiere de la razón social)'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='sri_obligado_contabilidad',
            field=models.BooleanField(default=False, verbose_name='Obligado a llevar contabilidad'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='sri_punto_emision',
            field=models.CharField(default='001', max_length=3, verbose_name='Código de punto de emisión (SRI)'),
        ),
    ]
