# Generated by Django 6.0.6 on 2026-07-15 15:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_configuracionsistema_sri_establecimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='retencion_porcentaje_default',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='% de retención por defecto (compras)'),
        ),
    ]
