# Generated by Django 6.0.6 on 2026-07-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_configuracionsistema_retencion_porcentaje_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='api_key_facturacion_electronica',
            field=models.CharField(blank=True, max_length=255, verbose_name='API key del microservicio de facturación electrónica'),
        ),
    ]
