# Generated by Django 6.0.6 on 2026-07-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_configuracionsistema_api_key_facturacion_electronica'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='empresa_id_facturacion_electronica',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID de empresa (microservicio de facturación electrónica)'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='sri_ambiente',
            field=models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], default='1', max_length=1, verbose_name='Ambiente (SRI)'),
        ),
    ]
