# Generated by Django 6.0.6 on 2026-07-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_configuracionsistema_empresa_id_facturacion_electronica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaFacturacionElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13, verbose_name='RUC')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón social')),
                ('direccion_matriz', models.CharField(max_length=255, verbose_name='Dirección matriz')),
                ('codigo_establecimiento', models.CharField(max_length=3, verbose_name='Código de establecimiento')),
                ('codigo_punto_emision', models.CharField(max_length=3, verbose_name='Código de punto de emisión')),
                ('ambiente', models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], default='1', max_length=1, verbose_name='Ambiente')),
                ('empresa_id_microservicio', models.CharField(max_length=50, verbose_name='ID de empresa en el microservicio')),
                ('api_key', models.CharField(max_length=255, verbose_name='API key')),
                ('activa', models.BooleanField(default=False, verbose_name='Activa')),
                ('fecha_conexion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de conexión')),
            ],
            options={
                'verbose_name': 'Empresa de facturación electrónica',
                'verbose_name_plural': 'Empresas de facturación electrónica',
                'ordering': ['-activa', '-fecha_conexion'],
            },
        ),
    ]
