# Generated by Django 6.0.6 on 2026-07-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0007_migrar_conexion_existente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='api_key_facturacion_electronica',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='empresa_id_facturacion_electronica',
        ),
    ]
