# Generated by Django 6.0.6 on 2026-07-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0002_cobrofactura_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrofactura',
            name='monto_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto recibido en efectivo'),
        ),
        migrations.AlterField(
            model_name='cobrofactura',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('paypal', 'PayPal')], default='efectivo', max_length=15, verbose_name='Forma de pago'),
        ),
    ]
