# Generated by Django 6.0.6 on 2026-07-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0003_cobrofactura_monto_recibido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cobrofactura',
            options={'ordering': ['-fecha', '-id'], 'permissions': [('access_cobrofactura_module', 'Acceso al módulo de cobros a clientes')], 'verbose_name': 'Cobro de Factura', 'verbose_name_plural': 'Cobros de Facturas'},
        ),
    ]
