# Generated by Django 6.0.6 on 2026-07-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0004_alter_cobrofactura_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrofactura',
            name='tarjeta_cvv',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='CVV/CVC'),
        ),
        migrations.AddField(
            model_name='cobrofactura',
            name='tarjeta_expiracion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de expiración de la tarjeta'),
        ),
        migrations.AddField(
            model_name='cobrofactura',
            name='tarjeta_titular',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Titular de la tarjeta'),
        ),
        migrations.AlterField(
            model_name='cobrofactura',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('paypal', 'PayPal')], default='efectivo', max_length=15, verbose_name='Forma de pago'),
        ),
    ]
