# Generated by Django 6.0.6 on 2026-07-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_grant_module_access_to_existing_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('send_whatsapp_userprofile', 'Puede enviar acceso al sistema por WhatsApp')], 'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
    ]
