"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path
import os
import sys

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga variables desde un .env local (no versionado) sin pisar variables de
# entorno reales del sistema/servidor (Render las define en su dashboard).
_env_path = BASE_DIR / '.env'
if _env_path.exists():
    for _line in _env_path.read_text(encoding='utf-8').splitlines():
        _line = _line.strip()
        if not _line or _line.startswith('#') or '=' not in _line:
            continue
        _key, _, _value = _line.partition('=')
        os.environ.setdefault(_key.strip(), _value.strip())

# =====================================================
# SEGURIDAD
# =====================================================

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-%9ymkup@n$n@xo)pfx^r+4h$(km*c(qk_iu9s0tkyoog_2_70p"
)

DEBUG = os.environ.get("DEBUG", "False") == "True"

ALLOWED_HOSTS = [
    "sales-project-dxoy.onrender.com",
    "localhost",
    "127.0.0.1",
]

CSRF_TRUSTED_ORIGINS = [
    "https://sales-project-dxoy.onrender.com",
]

# =====================================================
# APLICACIONES
# =====================================================

# Las primeras 6 son apps que YA trae Django (autenticación, sesiones,
# mensajes flash, panel /admin/, etc.) — sin 'django.contrib.auth' no
# existiría ni siquiera el modelo User que usa todo security/. Las nuestras
# (billing, purchasing, security, home) van después. Si creas una app nueva
# con `python manage.py startapp mi_app`, hay que agregarla acá para que
# Django la reconozca (sus modelos, templates, management commands, etc.).
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'billing',
    'purchasing',
    'security',
    'home',
    'django_extensions',
    'pagos',
    'cobros',
    'caja',
    'devoluciones',
    'notificaciones',
    'reportes',
    'configuracion',
    'paypal_pagos',
    'facturacion_electronica',
    'RRHumanos',
]

# =====================================================
# MIDDLEWARE
# =====================================================

# El middleware es una "cadena" por la que pasa CADA request antes de llegar
# a la vista, y CADA response antes de salir al navegador — en el orden en
# que están listados acá (de arriba hacia abajo en el request, al revés en
# el response). Ej: AuthenticationMiddleware es lo que hace que
# request.user exista en cualquier vista.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # sirve archivos estáticos en producción, sin necesitar nginx

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

# =====================================================
# TEMPLATES
# =====================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'notificaciones.context_processors.notificaciones',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# =====================================================
# BASE DE DATOS
# =====================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'dbventas.sqlite3',
    }
}

# =====================================================
# VALIDACIÓN DE CONTRASEÑAS
# =====================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# =====================================================
# INTERNACIONALIZACIÓN
# =====================================================

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# =====================================================
# ARCHIVOS ESTÁTICOS
# =====================================================

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# =====================================================
# ARCHIVOS MULTIMEDIA
# =====================================================

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# =====================================================
# LOGIN
# =====================================================

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# URL pública del sistema, usada en los correos/WhatsApp de credenciales para
# que el enlace siempre apunte al sitio real, sin importar desde dónde el
# administrador esté operando (local o producción).
SITE_URL = os.environ.get('SITE_URL', 'https://sales-project-dxoy.onrender.com')

# =====================================================
# EMAIL (Gmail SMTP)
# =====================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# =====================================================
# WHATSAPP (Twilio)
# =====================================================
# TWILIO_WHATSAPP_FROM debe incluir el prefijo 'whatsapp:', ej: 'whatsapp:+14155238886'

TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_WHATSAPP_FROM = os.environ.get('TWILIO_WHATSAPP_FROM', '')

# =====================================================
# TELEGRAM
# Un solo bot/chat para las alertas internas del sistema (stock bajo,
# diferencia de caja, vencimientos) — ver shared/notifications.py ->
# send_telegram_message() y notificaciones/services.py.
# TELEGRAM_BOT_TOKEN: lo da @BotFather al crear el bot (habla con
# https://t.me/BotFather en Telegram y usa /newbot).
# TELEGRAM_CHAT_ID: el ID del chat/grupo donde el bot debe mandar los
# avisos — se obtiene agregando el bot a ese chat/grupo y consultando
# https://api.telegram.org/bot<TOKEN>/getUpdates después de mandarle
# cualquier mensaje al bot ahí.
#
# OJO: en `manage.py test` estas dos quedan vacías a propósito, aunque el
# .env tenga credenciales reales — notificaciones/signals.py dispara
# send_telegram_message() en CUALQUIER alta/edición/borrado de las apps
# rastreadas, así que sin este corte la suite completa mandaría cientos de
# mensajes reales al chat de Telegram del desarrollador en cada corrida
# (y sería mucho más lenta por la red real). Los tests que sí quieren
# probar el envío usan @override_settings(TELEGRAM_BOT_TOKEN=...,
# TELEGRAM_CHAT_ID=...) explícito, que siempre gana sobre esto.
_EJECUTANDO_TESTS = 'test' in sys.argv

TELEGRAM_BOT_TOKEN = '' if _EJECUTANDO_TESTS else os.environ.get('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_CHAT_ID = '' if _EJECUTANDO_TESTS else os.environ.get('TELEGRAM_CHAT_ID', '')

# =====================================================
# PAYPAL
# =====================================================
# Client ID/Secret de una app en developer.paypal.com (Sandbox para pruebas,
# Live para producción). PAYPAL_WEBHOOK_ID se obtiene al registrar el webhook
# en el dashboard de PayPal (apunta a /paypal/webhook/) y se usa para
# verificar que las notificaciones realmente vienen de PayPal.

PAYPAL_CLIENT_ID = os.environ.get('PAYPAL_CLIENT_ID', '')
PAYPAL_CLIENT_SECRET = os.environ.get('PAYPAL_CLIENT_SECRET', '')
PAYPAL_WEBHOOK_ID = os.environ.get('PAYPAL_WEBHOOK_ID', '')
PAYPAL_MODE = os.environ.get('PAYPAL_MODE', 'sandbox')  # 'sandbox' o 'live'

# =====================================================
# SRI - Facturación Electrónica (Ecuador)
# =====================================================
# La firma/envío al SRI ya NO vive en este proyecto — se movió a un
# microservicio aparte (Railway), pensado para poder reutilizarse desde
# cualquier otro proyecto, no solo este. Acá solo queda el lado CLIENTE: la
# URL de ese servicio (ver facturacion_electronica/services.py y
# shared/notifications.py -> send_whatsapp_message). La API key para
# autenticarse contra él NO vive acá — puede haber VARIAS empresas
# conectadas (configuracion.EmpresaFacturacionElectronica), cada una con la
# suya, y se usa la que esté marcada activa=True (editable desde
# Configuración > Facturación Electrónica, sin redeploy). El certificado
# .p12 y SRI_AMBIENTE se configuran en el .env DE ESE SERVICIO, no acá.
FACTURACION_ELECTRONICA_SERVICE_URL = os.environ.get(
    'FACTURACION_ELECTRONICA_SERVICE_URL', 'http://localhost:8002'
)
FACTURACION_ELECTRONICA_SERVICE_TIMEOUT = float(os.environ.get('FACTURACION_ELECTRONICA_SERVICE_TIMEOUT', '10'))

# API key para el endpoint de verificación de facturas ante el SRI (ver
# facturacion_electronica/views.py -> verificar_autorizacion_api), usada
# por clientes EXTERNOS que llaman esa API sin sesión Django (header
# X-API-Key). Vacío por defecto = ese acceso queda deshabilitado hasta
# configurarlo — el uso interno (sesión + permiso) no depende de esto. Es un
# secreto DISTINTO del de arriba: este lo usan clientes externos para
# preguntarle A ESTE proyecto por una factura; el de arriba lo usa este
# proyecto para hablarle AL microservicio.
SRI_VERIFICACION_API_KEY = os.environ.get('SRI_VERIFICACION_API_KEY', '')

# =====================================================
# MESSAGES
# =====================================================
# Bootstrap 5 only defines .alert-danger, not .alert-error (Django's
# default tag for messages.error()), so without this remap error
# messages render with no styling and are effectively invisible.
from django.contrib.messages import constants as message_constants
MESSAGE_TAGS = {
    message_constants.ERROR: 'danger',
}

# =====================================================
# DEFAULT AUTO FIELD
# =====================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'