# Generated by Django 6.0.6 on 2026-07-16 15:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHumanos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('tasa_interes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Tipo de Préstamo',
                'verbose_name_plural': 'Tipos de Préstamo',
            },
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('interes', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('monto_pagar', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('numero_cuotas', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('saldo', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('PAG', 'Pagado'), ('ANU', 'Anulado')], default='PEND', max_length=4)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHumanos.empleado')),
                ('tipo_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHumanos.tipoprestamo')),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='RRHumanos.prestamo')),
            ],
            options={
                'verbose_name': 'Detalle de Préstamo',
                'verbose_name_plural': 'Detalles de Préstamo',
                'ordering': ['numero_cuota'],
            },
        ),
    ]
