# Generated by Django 6.0.6 on 2026-07-16 15:44

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHumanos', '0002_tipoprestamo_alter_empleado_sueldo_prestamo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_fin_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date(2020, 1, 1)),
        ),
        migrations.AddField(
            model_name='tipoprestamo',
            name='monto_maximo',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='tipoprestamo',
            name='tasa_interes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
