# Generated by Django 6.0.6 on 2026-07-16 15:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHumanos', '0003_empleado_fecha_fin_contrato_empleado_fecha_ingreso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Límite de Crédito'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asociado'),
        ),
    ]
