# Generated by Django 6.0.6 on 2026-07-16 15:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHumanos', '0004_empleado_limite_credito_empleado_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='porcentaje_credito',
            field=models.PositiveIntegerField(default=300, help_text='Porcentaje del salario asignado como límite de crédito. Ej. 300% equivale a 3 veces su sueldo.'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Límite de Crédito'),
        ),
    ]
