# Generated by Django 6.0.6 on 2026-07-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_purchase_estado_purchase_saldo_purchase_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='meses_credito',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Meses para diferir'),
        ),
    ]
