# Generated by Django 6.0.6 on 2026-07-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_purchase_meses_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='interes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Interés'),
        ),
    ]
