# Generated by Django 6.0.6 on 2026-07-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_purchase_interes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date'], 'permissions': [('access_purchase_module', 'Acceso al módulo de compras')], 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
    ]
