# Generated by Django 6.0.6 on 2026-07-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0006_alter_purchase_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date'], 'permissions': [('access_purchase_module', 'Acceso al módulo de compras'), ('export_pdf_purchase', 'Puede exportar compras a PDF'), ('export_excel_purchase', 'Puede exportar compras a Excel')], 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
    ]
