# Generated by Django 6.0.6 on 2026-07-15 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0007_alter_purchase_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='factura_adjunta',
            field=models.FileField(blank=True, null=True, upload_to='purchases/facturas/', verbose_name='Factura del proveedor (PDF/XML/imagen)'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='fase',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('recibida', 'Recibida')], default='borrador', max_length=10, verbose_name='Fase'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='fecha_entrega_estimada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha estimada de entrega'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='retencion_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Retención (%)'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='retencion_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Retención (valor)'),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='purchasing.bodega', verbose_name='Bodega de destino'),
        ),
    ]
