# Generated by Django 6.0.6 on 2026-07-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0008_bodega_purchase_factura_adjunta_purchase_fase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='fecha_entrega_estimada',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='retencion_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Retención (%)'),
        ),
    ]
