# Generated by Django 6.0.6 on 2026-07-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0009_remove_purchase_fecha_entrega_estimada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('paypal', 'PayPal')], max_length=15, null=True, verbose_name='Forma de pago'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='paypal_payout_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de payout de PayPal'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tarjeta_cvv',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='CVV/CVC'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tarjeta_expiracion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de expiración de la tarjeta'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tarjeta_titular',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Titular de la tarjeta'),
        ),
    ]
