# Generated by Django 6.0.6 on 2026-07-13 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('pagos', '0002_pagocompra_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='pago_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='pagos.pagocompra', verbose_name='Pago a proveedor relacionado'),
        ),
    ]
