# Generated by Django 6.0.6 on 2026-07-13 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_movimientocaja_pago_compra'),
        ('cobros', '0002_cobrofactura_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='cobro_factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='cobros.cobrofactura', verbose_name='Cobro de factura relacionado'),
        ),
    ]
