# Generated by Django 6.0.6 on 2026-07-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_movimientocaja_cobro_factura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesioncaja',
            options={'ordering': ['-fecha_apertura'], 'permissions': [('access_sesioncaja_module', 'Acceso al módulo de caja')], 'verbose_name': 'Sesión de Caja', 'verbose_name_plural': 'Sesiones de Caja'},
        ),
    ]
