# Generated by Django 6.0.6 on 2026-07-16 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_alter_sesioncaja_options'),
        ('purchasing', '0010_purchase_forma_pago_purchase_paypal_payout_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='purchasing.purchase', verbose_name='Compra relacionada'),
        ),
    ]
