# Generated by Django 6.0.6 on 2026-07-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devolucionventa',
            options={'ordering': ['-fecha'], 'permissions': [('access_devolucionventa_module', 'Acceso al módulo de devoluciones')], 'verbose_name': 'Devolución de Venta', 'verbose_name_plural': 'Devoluciones de Ventas'},
        ),
    ]
